[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
app = "AaYfvcZY1iUVFM33KAKUNh8g4JPsStcgp88admDTTMVH"
fhe_lib = "Fuj5qpvT66C7pz4fvyLDV6d8YCUS9idJH2i66Qj5vedh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
